export type ProjectStat = { value: string; label: string }
export type ProjectSection = { title: string; body: string; image?: string }

export type Project = {
  slug: string
  title: string
  company: string
  thumbnail: string
  thumbnailColor?: string
  images: string[]
  description: string
  stats?: ProjectStat[]
  sections?: ProjectSection[]
  thinContent?: boolean
  link?: string
  imageLabels?: Record<number, string>
}

export const COMPANIES = ['All', 'AI Builds', 'Take-Homes', 'Conmetior', 'Marin Mountain School', 'Bad Cards', 'Gametime', 'Lyft', 'Robinhood', 'Concept Labs', 'AirPR', 'Other'] as const

export const PROJECTS: Project[] = [
  {
    slug: 'hot-or-cold',
    title: 'Hot or Cold',
    company: 'AI Builds',
    thumbnail: '/portfolio/hot-or-cold-hero-card.jpg',
    thumbnailColor: '#0d0d0d',
    images: [
      '/portfolio/hot-or-cold-hero.png',
      '/portfolio/hot-or-cold-round-recap.png',
      '/portfolio/hot-or-cold-lobby.png',
      '/portfolio/hot-or-cold-after-dark-pack.png',
    ],
    imageLabels: {
      1: 'Every round ends as a shareable recap: the clue, where each player guessed, and the answer',
      2: 'The lobby. Room code, pack picker, game length, pace and mode',
      3: 'Packs gate both content and tone. After Dark is age gated and sold separately',
    },
    link: 'https://hotorcold.app',
    description: 'Hot or Cold is a real-time multiplayer party game. One player gets a hidden number on a spectrum like Overrated to Underrated. They write a single clue. Everyone else places a dial where they think it sits. The arguing is the game.\n\nIt is also a measurement instrument. Most human preference data is either scraped without permission or collected in a lab, where people answer differently because they know they are being watched. This is a third option. A game people want to play on a Friday night, where playing produces a clean consented record of how a person judges things. Invisible at the table, rigorous in the database.\n\nBuilt solo across five months and 176 commits: the game, the content, the infrastructure and the research layer. Real players arrived in July 2026. The corpus now holds 45,935 guesses from 6,997 people.',
    stats: [
      { value: '45,935', label: 'Guesses recorded' },
      { value: '14,367', label: 'Rounds captured' },
      { value: '6,997', label: 'Players' },
      { value: '8,809', label: 'Clues written by players' },
      { value: '+7.0 pts', label: 'Knowing the person beats knowing the corpus, across 1,051 people' },
      { value: '260', label: 'Spectrums across 6 packs' },
      { value: '16', label: 'Languages' },
      { value: '176', label: 'Commits, solo, May to September 2026' },
    ],
    sections: [
      {
        title: 'The stack',
        body: 'TypeScript pnpm monorepo in four packages. Fastify 5 with Colyseus 0.16 holds live rooms over WebSocket on Fly.io. React 18.3 with Vite 6 and TanStack Router on Cloudflare Pages. Neon Postgres with Drizzle, 16 tables and 10 migrations. Auth is an emailed code, no passwords. It also ships as a Discord Activity that runs inside a voice channel with nothing to install.\n\nEvery round writes a versioned JSONB payload rather than a fixed row, so the capture schema can change without orphaning history. Player identifiers are salted one-way hashes and consent is versioned, so it is always clear which terms a given row was collected under.',
      },
      {
        title: 'The modes measure different things',
        body: 'The round types are not variety for its own sake. Classic gives one player a hidden target and one clue, and measures whether meaning survives the trip between two people. Crowd Read asks for your own position and your prediction of the room on the same item, which is the pairing almost no dataset has. Hot Seat puts one player on the spectrum and everyone else places them, which is the only mode that captures how a group sees an individual.\n\nHot Seat is also the most sensitive thing in the system, so it never leaves in any external dataset. Poles are randomised every round so left and right carry no fixed meaning, with the canonical orientation stored alongside so analysis is not fooled by the flip.',
      },
      {
        title: 'The measurement result',
        body: 'The benchmark asks a predictor to pick which of four clues a specific person wrote, with the three decoys drawn from the same spectrum by different authors. Chance is 25 percent.\n\nA predictor that knows the whole clue corpus but nothing about the person scores 24.3 percent, which is chance. A predictor that knows the person scores 31.3 percent. That gap is seven points across 1,051 people.\n\nThe comparison is deliberately personal against population rather than personal against chance. Scoring a personal predictor against chance quietly takes credit for everything general knowledge already earns, which is how this kind of result usually gets overstated.',
      },
      {
        title: 'Building solo with a model',
        body: 'No model runs inside a round. Bots play from a precomputed clue bank, not live inference. A forty second timer is the wrong place for an inference call, and a model in the request path would have made the game slower and the data noisier.\n\nThe models are in how it got built. Claude Code wrote most of the lines across five months while I designed the game, the modes, the data model and the measurement, and reviewed every change. The split held because the model is fast at producing code and has no opinion about whether a round type earns its place, whether a number is honest, or whether a field is safe to publish.\n\nThe clearest example is the measurement work. I asked for the analysis that tested my own assumption about how well people read each other, and the answer came back weaker than the pitch. Publishing the weaker number is the entire point of having built an instrument rather than a demo.',
      },
    ],
  },
  {
    slug: 'conmetior-connect',
    title: 'Conmetior Connect',
    company: 'Conmetior',
    thumbnail: '/portfolio/conmetior-connect-home-card.jpg',
    images: [
      '/portfolio/conmetior-connect-home.png',
      '/portfolio/conmetior-connect-posts.png',
      '/portfolio/conmetior-connect-dashboard.png',
      '/portfolio/conmetior-connect-wizard.png',
      '/portfolio/conmetior-connect-audit.png',
    ],
    imageLabels: {
      1: 'The core screen: a month of generated posts waiting for approval',
      2: 'Practice dashboard, including the plain-English recovery banner',
      3: 'Brand profile built during onboarding: practice type, detected voice',
      4: 'The free practice audit, the top of the funnel and the lead capture',
    },
    link: 'https://conmetiorconnect.com',
    description: 'When someone needs a dentist they search Google and call one of the first practices that looks active. The Google Business Profile is the storefront that decides whether that call comes in. Most practices have not posted to theirs in months, not because it does not matter, but because the work is weekly, unrelenting and nobody\'s job.\n\nConmetior Connect is a subscription product that keeps that profile working without adding anything to the practice\'s week. It writes their posts in the voice detected from their own site and reviews, drafts replies to reviews in whatever language the reviewer used, monitors profile health daily, and publishes only what the practice approves. Approval takes about a minute a week from a phone.\n\nThe product is live and functional. It has not yet been sent to its target list, so the numbers below measure the build and the targeting research rather than adoption.',
    stats: [
      { value: '192', label: 'Commits, May to September 2026' },
      { value: '30', label: 'Database tables across 29 migrations' },
      { value: '11', label: 'Scheduled jobs running the automation' },
      { value: '10', label: 'Languages, 7,600 translation keys' },
      { value: '16,784', label: 'Dental practice websites analyzed and scored' },
      { value: '73,821', label: 'Customer contacts classified into 31,916 domains' },
      { value: '1,899', label: 'Targets found already running a competitor, and deprioritized' },
    ],
    sections: [
      {
        title: 'The compliance gate',
        body: 'Dental has a constraint most content tools ignore. Healthcare advertising rules differ by market, and a post that promises an outcome or quotes a price creates a real problem for the practice rather than just a bad impression.\n\nEvery generated post is graded against a dental advertising ruleset before a human sees it, with a stricter European variant outside the US. The grader fails closed. If it cannot run, nothing publishes. The product\'s whole promise is that a practice can stop watching, so the failure mode had to be silence rather than a bad post going out under their name.\n\nTwo models split the work. Sonnet 5 writes anything a dentist or a patient will read. Haiku 4.5 handles classification and extraction, where quality is invisible and volume is high.',
      },
      {
        title: 'Ten languages, not ten translations',
        body: 'The product ships in ten languages across 7,600 keys, but the localization goes past the interface. Generated content is written natively in the practice\'s language rather than translated afterward, review replies match the language the reviewer wrote in, and the compliance ruleset switches standard by market. A validation script runs in the build and blocks retired pricing, unapproved claims and stylistic violations from reaching any locale.',
      },
      {
        title: 'Targeting research: 73,821 contacts down to 300',
        body: 'The client had a customer list of 73,821 contacts across 31,916 business domains and no idea which to email. Sorting by contact volume would have surfaced the DSO chains, which are the opposite of the buyer.\n\nI wrote a pipeline that filtered out chains, government, universities, suppliers and international domains, then visited all 16,784 remaining dental practice websites and scored each on how visibly unattended its presence was and how likely it was to buy. Practices already running Birdeye, Podium or Weave were pushed down automatically, which found 1,899 of them. The output was a ranked first send of 300 with a plain English reason attached to every row.',
      },
      {
        title: 'Rebuilding the funnel around a free audit',
        body: 'The first version asked a cold prospect to create an account, connect their Google profile and enter a card as the first step. Real clicks produced no signups.\n\nThe replacement leads with a free audit that asks only for a URL, returns a graded report on how the practice looks to a new patient, and writes two real posts for that specific practice in exchange for an email. It also solved a writing problem. Research on a stranger cannot be used in a cold email without sounding like surveillance, but the same specificity is the product once they have asked for the analysis.',
      },
    ],
  },
  {
    slug: 'forterra-compliance-checker',
    title: 'Pre-Flight Compliance Checker',
    company: 'Take-Homes',
    thumbnail: '/portfolio/forterra-hero-card.jpg',
    thumbnailColor: '#1a1a1a',
    images: [
      '/portfolio/forterra-hero.png',
      '/portfolio/forterra-flags.png',
      '/portfolio/forterra-attributed.png',
    ],
    imageLabels: {
      1: 'Every flag carries severity, an explanation, a one-click rewrite and the regulation it comes from',
      2: 'Claims inside an attributed external quote are downgraded rather than flagged as hard violations',
    },
    link: 'https://forterra-press-generator.vercel.app/compliance',
    description: 'Built for Forterra, an autonomous defense vehicle company, during a final-round interview.\n\nDefense marketing carries risk most marketing teams are not equipped to catch. One line in a press release can cross ITAR, OPSEC, EAR, DFARS or foreign disclosure rules, and the person writing it usually has no way to know. The safety net is legal review, which is slow, arrives late, and turns every draft into a queue.\n\nSo I built a tool that reads draft marketing content and flags those problems before anything ships. Paste a draft, pick the content type and where it is going, run the check. It returns a score and every issue it found, each one carrying the exact text that triggered it, a severity, a plain explanation, the regulation it comes from cited properly, and a suggested compliant rewrite you can accept with one click. Re-run, and the score moves.\n\nIt scored clean copy at 86 to 95 percent and unfiltered drafts near zero, catching real violations on live Forterra content. It shipped as a deployed working tool rather than a mockup, and it is still running.',
    stats: [
      { value: '6', label: 'Regulatory frameworks in the rule library' },
      { value: '18', label: 'Rules, each with a citation and a suggested rewrite' },
      { value: '11', label: 'Violations caught in the sample draft' },
      { value: '0% to 95%', label: 'Score range, unfiltered draft to cleaned copy' },
      { value: '6 days', label: 'First commit to deployed demo' },
      { value: '1,502', label: 'Lines of TypeScript across the app' },
    ],
    sections: [
      {
        title: 'The rule library is the product',
        body: 'Anyone can build a text box that highlights words. The work was deciding what actually constitutes a violation and proving it.\n\nEach rule pairs a pattern with a real citation. 22 CFR 120-130 and USML Category XII for sensor and targeting specifications. AR 530-1 and DoDD 5205.02E for unit identification. DFARS 252.204-7000 and FAR 3.104 for procurement integrity. 15 CFR 730-774 for dual-use characterisation.\n\nThe rewrite matters as much as the flag. Telling a marketer that a sensor range of 2.3km is a problem is half the job. Handing them extended-range sensor capability is the other half.',
      },
      {
        title: 'Attributed quotes get different treatment',
        body: 'An executive quote is not the same liability as a company claim, and treating them identically would have made the tool annoying enough to ignore. The checker detects when flagged language sits inside an attributed external quote and downgrades it, marking it as reduced liability but still worth review.\n\nThat single rule is the difference between a tool a team uses and one they route around.',
      },
      {
        title: 'No model in the loop, on purpose',
        body: 'The checker is deterministic. A compliance tool that invents a citation is worse than no tool, because it teaches people to distrust it at exactly the moment they need it. Every flag traces to a written rule a compliance officer can read, argue with and amend.\n\nClaude Code wrote the application. I wrote the rule library, did the regulatory research behind every citation, made the product and interface decisions, and checked each rule against the actual CFR and DoD sources.',
      },
      {
        title: 'What it changes',
        body: 'It turns a slow legal review bottleneck into a self-serve check anyone on the marketing team can run before they send anything. Legal still reviews, but they review drafts that have already had the obvious problems removed, with the reasoning attached.\n\nContent types cover press release, LinkedIn post, blog, web copy, exec quote, spec sheet and trade show material. Destinations cover US public, allied NATO nations, restricted and internal only, because the same sentence can be fine in one context and a violation in another.',
      },
    ],
  },
  {
    slug: 'radical-health-acquisition',
    title: 'Radical Health, D2C Patient Acquisition',
    company: 'Take-Homes',
    thumbnail: '/portfolio/radical-health-hero-card.jpg',
    thumbnailColor: '#D55E3F',
    images: [
      '/portfolio/radical-health-hero.png',
      '/portfolio/radical-health-meta-ads.jpg',
      '/portfolio/radical-health-landing.jpg',
      '/portfolio/radical-health-serp.png',
    ],
    imageLabels: {
      1: 'Three Meta creatives built on Radical’s own assets: their hero film, a real patient portrait, and their report UI',
      2: 'The paid landing page, built as a landing page rather than a homepage',
      3: 'One of two Google responsive search ads',
    },
    link: 'https://heynatefox.com/radical',
    description: 'A growth take-home for Radical Health, an AI oncology platform that returns a complete report of a patient\'s treatment options in 24 hours. The brief: pick one segment and moment, write the ads and the landing page for real, and plan $50K across Google and Meta.\n\nI picked the treatment-decision window. A plan has been proposed, a start date exists, and in the two to four weeks between them one question sits in the room without a good way to answer it. Is this everything, or is this the first thing? That window is the only moment where a 24 hour report changes anything, which is the entire argument for it over any other segment.\n\nThe wedge is completeness, not correctness. Correctness framing asks whether the plan is right, which puts the product against the oncologist and crosses a compliance line the team cannot cross. Completeness asks whether the full option set is visible. It never grades the plan, and it is already their own headline.\n\nSpec work. It was never run, so there is no performance data here. Everything below is the deliverable and the reasoning.',
    stats: [
      { value: '$50K', label: 'Planned across Google Search and Meta' },
      { value: '5', label: 'Ad variants, written and rendered as mockups' },
      { value: '1', label: 'Landing page, built rather than described' },
      { value: '2 to 4 weeks', label: 'The decision window the whole plan targets' },
      { value: '65/35', label: 'Search to Meta split, by where intent is legible' },
      { value: '~2.5 hrs', label: 'Build time end to end' },
    ],
    sections: [
      {
        title: 'One moment, two people',
        body: 'Two people occupy that window, and the channel decides which one you reach. On Google the query does the targeting, so whoever types stage 2 lung cancer treatment options has told you everything.\n\nOn Meta you cannot target a health condition at all. Detailed targeting for health was removed in 2022, and policy forbids an ad implying it knows the viewer\'s health status. So the creative does the qualifying, and the only person an ad can legally address is the caregiver. Roughly 43 percent of health information seekers are researching for someone else, and they are the ones who go online first. The constraint and the best strategy point the same direction.',
      },
      {
        title: 'Five ads, built in their system',
        body: 'Two Google responsive search ads and three Meta concepts, all written to run as is.\n\nThe Meta creatives are built on Radical\'s own assets rather than invented ones: the still from their hero film behind the caregiver headline, a real patient\'s portrait cropped the way their site crops it, and the three option cards lifted straight out of the actual report. Their licensed display face is self-hosted so the type is theirs, and their headline underline device is reused exactly.\n\nWhat is not in any of them: no countdown, no urgency device of any kind. The urgency is already in the room. Manufacturing more of it is the fastest way to lose this audience permanently. Calm is the differentiated position in a feed full of people shouting at sick people.',
      },
      {
        title: 'A paid landing page, not a homepage',
        body: 'The landing page is deliberately not their homepage. Logo only, no navigation, one CTA repeated once, seven blocks, message-matched to the ad that drove the click. It uses the real report screenshot as the proof rather than describing it.\n\nThe sequencing is built around where the funnel actually leaks. The first conversion is a three-field coverage check, which is easy. The real drop is at records connection, the moment a stranger on the internet asks for access to your medical file. So the page names the records step before the click, names the 70,000 institution network to turn an act of trust into an act of logistics, and puts the NCCN advisors and the nurse above the form, because the question people are really asking is not is this secure, it is is this real.',
      },
      {
        title: 'The metric and the two-week plan',
        body: 'The number on the wall is cost per records-connected patient, not cost per coverage check. A check with no records behind it produces a generic report and a dead relationship, and counting it makes a channel look good while it wastes money.\n\nWeek one changes nothing except negative keywords. The instinct to optimise on day three is the most expensive instinct in paid acquisition at this budget. End of week two the kill, scale and pause thresholds are already written down and agreed, including killing any ad whose coverage checks connect records under 40 percent even if its cost per check is the best in the account, because it is buying the wrong person.\n\nOne honest note carried on the page: price sits behind the coverage check, so contribution margin and a true allowable CAC could not be modelled from outside. Every threshold is a starting hypothesis to be replaced by week one data.',
      },
    ],
  },
  {
    slug: 'gamma-just-a-sec',
    title: 'Need a deck? just a sec.',
    company: 'Take-Homes',
    thumbnail: '/portfolio/gamma-just-a-sec-three-hooks-card.jpg',
    thumbnailColor: '#0d0d0d',
    images: [
      '/portfolio/gamma-just-a-sec-three-hooks.jpg',
      '/portfolio/gamma-just-a-sec-product-take.jpg',
      '/portfolio/gamma-just-a-sec-statics.jpg',
      '/portfolio/gamma-just-a-sec-figma-parts.jpg',
    ],
    imageLabels: {
      1: 'The product take. One unbroken 11.1 second shot, captions set above the UI',
      2: 'Three statics at 4:5, 1:1 and 9:16, rendered from the same config as the video',
      3: 'The component library. Every piece exported on its own at 3x, transparent',
    },
    link: 'https://heynatefox.com/gamma',
    description: 'A paid social campaign for Gamma, produced as a take-home for an AI Creative Strategist role.\n\nThe brief asked for three video variants, statics in three ratios, and a process note. The normal way to do that is screen record the product, cut it in Premiere, hand back three exports. That gets you three assets. It does not get you a fourth.\n\nThe real constraint in paid social is not making one good ad. A creative that works on Meta is spent in two to three weeks, so the number that governs cost over a quarter is how fast the replacement lands. So I set a different problem: build the asset in a way where the thirtieth variant costs about what the fourth did.\n\nThe product UI in these spots is not a screen recording. It is rebuilt as vector in plain HTML and CSS, driven by a deterministic seek function that returns the exact state of any frame at any time. Puppeteer steps that one frame at a time in headless Chrome and pipes PNGs into ffmpeg, so every run is frame identical. Because the frame is a pure function of time, everything describing the ad is data: copy, timing, camera keyframes, captions, slides. Changing the concept is editing a config, not reopening a design file.',
    stats: [
      { value: '3', label: 'Videos at 20.00s, 1080x1920, one shared spine' },
      { value: '2,663', label: 'Lines of render engine across 13 files' },
      { value: '5', label: 'Output ratios from one config' },
      { value: '65', label: 'Figma-ready components exported at 3x' },
      { value: '182', label: 'Files delivered across 13 folders' },
      { value: '50 min', label: 'To rebuild after the concept changed completely' },
      { value: '3 days', label: 'First render to final cut' },
    ],
    sections: [
      {
        title: 'Three hooks, one spine',
        body: 'Three genuinely different openers run against one identical middle. A person reading the message, a team channel where the ask is already sitting there, and a title card that states the need with no setup. Each is a hypothesis about a different axis: a face buys attention, a channel buys recognition, a line buys clarity.\n\nThe middle never changes, because the middle is where viewers leave. It is one unbroken 11.1 second take of the real product flow that never cuts away from the screen, so the payoff and the product are the same shot. All three land on 20.00 seconds exactly, because each opener buys its length out of its own close.',
      },
      {
        title: 'Building the system before the output',
        body: 'The first pass built the engine, not the spot. That is the whole bet, and it is visible in the file structure: 2,663 lines of engine across 13 files, then three finished videos that are each a short config on top of it.\n\nIt paid off twice. Once when the concept changed completely mid-build, which cost 50 minutes instead of a restart, and the previous concept still renders untouched from its archived config. Again on every round of revisions, where a note like the captions are in the wrong place is a coordinate change and a re-render rather than a re-edit.',
      },
      {
        title: 'Diagnosing motion by measuring it, not watching it',
        body: 'Several rounds of feedback were about a transition feeling choppy. Watching it back and guessing produced three failed fixes.\n\nTracking the object frame by frame found the cause in one pass. The canvas clipped content flat against the page with no visible boundary, so the final slide\'s bottom edge sat pinned on the clip line for thirteen consecutive frames while its top climbed. It was not scrolling into place. It was inflating, because the bottom physically could not move.\n\nThe same approach fixed the cut into the send beat. Measuring pixel difference across the cut gave a number to work against: 117,677 differing pixels before, 305 after. That is the difference between an edit that reads as a scene change and one that is invisible.',
      },
      {
        title: 'Handed over as a system',
        body: '182 files across 13 folders, not three exports. Alpha layers on ProRes 4444 and VP9 so any line can be reworded without touching the base. A 65 piece component library for Figma. A build script where changing one constant re-cuts all three videos consistently. The statics render from the same config as the video, which is why the times on screen match across all of it.\n\nI wrote none of the code by hand. Claude Opus 5 through Claude Code built the engine, the overlay layers and the build script, and drove every render. The concept, the campaign line, the hook structure, the pacing and every creative call were mine, and several rounds were rejected and rebuilt on my direction. The AI is in how it was made, not in what plays.',
      },
    ],
  },
  {
    slug: 'marin-mountain-school',
    title: 'Marin Mountain School',
    company: 'Marin Mountain School',
    thumbnail: '/portfolio/marin-mountain-school-home-card.jpg',
    images: [
      '/portfolio/marin-mountain-school-home.jpg',
      '/portfolio/marin-mountain-school-community.jpg',
      '/portfolio/marin-mountain-school-admissions.png',
      '/portfolio/marin-mountain-school-apply.png',
      '/portfolio/marin-mountain-school-mobile.png',
      '/portfolio/marin-mountain-school-share-card.jpg',
    ],
    imageLabels: {
      1: 'Community page, one of twelve designed templates',
      2: 'Admissions',
      3: 'The school’s existing 65-field Gravity Form, restyled and left running',
      4: 'Homepage at 390px',
      5: 'Social share card, generated from the site’s own logo and brand fonts',
    },
    link: 'https://www.marinmountainschool.org',
    description: 'A 35-year-old preschool in Corte Madera wanted a rebuild. The design was dated and the site looked it.\n\nThe rebuild was most of the way done as a custom Next.js site before the real constraint surfaced. The school does not just publish pages. It takes money and runs admissions through that site. Nine Gravity Forms, live Stripe, a 65-field admission application with a fee attached, a named scholarship fund, and nine years of submitted entries behind them. At the point the new site was ready to launch, 292 applications and 372 contact messages were already in that system.\n\nSo the actual problem was not design. A beautiful new site on a different stack would have orphaned a working payment pipeline during admissions season, and the director who runs it is not technical and had no appetite for learning a second system.\n\nI abandoned the Next.js deployment and ported the design into their existing WordPress instead. Forms, payments and entry history stayed exactly where they were, it cost the school nothing new, and it removed a hosting bill rather than adding one.',
    stats: [
      { value: '18', label: 'Page templates in the shipped theme' },
      { value: '292', label: 'Admission applications the redesign had to not break' },
      { value: '9', label: 'Existing Gravity Forms preserved, including a 65-field application' },
      { value: '54', label: 'Editable fields exposed to the school' },
      { value: '3,649', label: 'Lines of PHP, JS and CSS in the theme' },
      { value: '0', label: 'Seconds of downtime at launch' },
    ],
    sections: [
      {
        title: 'The audit that changed the plan',
        body: 'I crawled all 24 pages of the live site and mapped every form to the page embedding it, which is what produced the finding the project turned on. The new-family application lived on a noindexed page nobody had mentioned. Tuition ran through FACTS Management rather than the parent portal everyone assumed. Two of the nine forms were embedded nowhere at all.\n\nIt also corrected the site\'s own copy. The donate page claimed gifts were processed through the parent portal. They were not. They ran through Gravity Forms and Stripe.',
      },
      {
        title: 'Launching without downtime',
        body: 'The theme was uploaded inactive, so it sat on the server changing nothing while the director reviewed it through WordPress Live Preview, which renders the new design for one logged-in session while every visitor still sees the old site.\n\nThe flip was activating the theme. Ten seconds, no database change, no downtime, and rollback was activating the old theme again. The one thing I refused to use was SiteGround\'s push-to-live, which overwrites the live database and would have destroyed any application submitted during the build window.\n\nOld pages I never designed still render, because the default template carries the full design language. Nothing 404s and nothing looks half-finished.',
      },
      {
        title: 'Making it editable by a non-technical director',
        body: 'The school\'s director does everything and is not comfortable with WordPress. The point of the ACF layer was to make her independent of me.\n\nEvery photo and every piece of global copy is exposed through ACF Pro as Local JSON, so field definitions live in git rather than trapped in a database. Templates read those fields with the current content hardcoded as a fallback, so the theme renders complete the moment it is activated and editing is optional instead of a prerequisite.\n\nShe gets a custom Welcome dashboard with large labeled cards for the tasks she actually does, and a How-To Guides page beside it with plain-language walkthroughs that print, because she prefers paper. Menus she does not need are hidden from non-admin roles, and Editors can read form entries without being able to touch plugins, payments or the design.',
      },
      {
        title: 'Copy under a trademark constraint',
        body: 'After launch the school was told by its accrediting association that the site could not use a specific pedagogical term in the domain, name, tagline, headers or links, and that the copy had to describe what the school does rather than what that tradition does.\n\nI rewrote the site to that rule. The headline changed, the FAQ was restructured so the school is the grammatical subject of every question and answer, page titles and schema descriptions were rewritten, eight alt texts were fixed and the share card was regenerated. Then I verified compliance against the live site rather than assuming it: zero occurrences in any page title, any h1 or h2, or any alt text across all 11 pages.\n\nThe positioning survived. The term still appears where the rules allow it, in full sentences on three pages and in teachers\' factual training credentials.',
      },
    ],
  },
  {
    slug: 'head-rush-kids',
    title: 'Head Rush Kids',
    company: 'AI Builds',
    thumbnail: '/portfolio/head-rush-kids-gameplay-card-card.jpg',
    thumbnailColor: '#0d0d0d',
    images: [
      '/portfolio/head-rush-kids-gameplay-card.png',
      '/portfolio/head-rush-kids-deck-store.png',
      '/portfolio/head-rush-kids-results.png',
      '/portfolio/head-rush-kids-paywall.png',
    ],
    imageLabels: {
      1: 'The deck store. Each tier states its price once in the section header',
      2: 'Results screen with a per-card recap',
      3: 'The unlock sheet, behind a press-and-hold gate so a child cannot trigger it',
    },
    link: 'https://headrushkids.com',
    description: 'Work in progress. The game is built, live and playable, but payments are still in Stripe test mode and nothing is instrumented, so there are no player, retention or revenue numbers here yet. It is in the portfolio for what it took to build, not for what it has done.\n\nHold a phone to your forehead, tilt down when your group gets the word, tilt up to skip, 60 seconds a round. 28 decks, 50 cards each, 1,400 cards total, every one a word plus a large emoji so a child who cannot read can still give the clue. It opens from a link with no install.\n\nThe reason it exists is that my own kids could not play the games in the app store. The good ones assume you can read, and every one of them charges again for content that should have shipped with it.\n\nThe reason it took a year is one bug.',
    stats: [
      { value: '1,400', label: 'Cards across 28 decks' },
      { value: '0', label: 'npm dependencies and no build step' },
      { value: '1,217', label: 'Lines of application code' },
      { value: '3', label: 'Unlock tiers: 4 free decks, 4 for an email, 20 paid' },
      { value: '6', label: 'Serverless endpoints' },
      { value: '3 months', label: 'That one motion bug stalled the project' },
    ],
    sections: [
      {
        title: 'The bug that stalled it for three months',
        body: 'A phone held flat against a forehead sits exactly where the browser orientation API breaks down. My first attempt read the gamma angle, which flips sign near vertical, so tilts registered twice or not at all. Three months of the project died on that.\n\nThe fix was to stop reading orientation angles and read the gravity vector instead. The devicemotion event reports acceleration including gravity, and the z component of that vector gives a clean pitch angle with no discontinuity in the forehead position. Tilt down is positive, tilt up is negative, and it behaves the same in both landscape directions.\n\nThat is the whole reason this project is worth showing. Not the game. The three months it took to learn that the obvious API was the wrong one.',
      },
      {
        title: 'Tuning it for a room full of kids',
        body: 'On top of the gravity vector sits the tuning that makes it feel right. Three sensitivity presets expressed in real degrees from vertical: 45, 35 and 25. A card only re-arms once the phone returns within 15 degrees of vertical and at least 400 milliseconds have passed, so one enthusiastic swing cannot burn two cards. A single sign constant flips the whole thing if a device reports gravity inverted.\n\nThere is a debug mode that prints live pitch and lets arrow keys drive the same code path, so most of the work could be tested on a laptop instead of by picking up a phone after every change.\n\nPortrait is for setup, landscape is for play. The round starts on its own when the phone turns and pauses if it turns back. Orientation events are unreliable across mobile browsers, so that runs off listeners plus a polling watchdog rather than trusting any single event to fire.',
      },
      {
        title: '1,400 cards, tagged at the source',
        body: 'Sixteen cards per deck was not enough. A deck ran out before the timer did. Getting every deck to 50 meant writing 952 new cards.\n\nI ran four Claude subagents in parallel, each owning seven decks, each working against the same fixed schema: a word, one emoji, and three tags covering what kind of thing it is, whether it is best acted, sounded or described, and whether it is real or fictional. They wrote to separate files and a merge script checked every card before it landed, rejecting duplicates within a deck and any invalid tag. All 28 decks came out at exactly 50 with no failures.\n\nThe tags are not decoration. They are the schema the capture layer records against.',
      },
      {
        title: 'Where it stands',
        body: 'Shipped: the game, 1,400 cards, the motion engine, the three-tier unlock, Stripe Checkout with session verification, two domains, a manifest and icons so it installs as a real web app, and a plain-language privacy policy written for parents.\n\nNot done: payments are in test mode, the capture layer and email list are unconfigured in production, and it has never been put in front of anyone at scale. The next step is the app stores, which is what the privacy policy and the installable wrapper were for.\n\nOne architectural note I would keep. The whole game is one HTML file, one data file and six serverless functions. No framework, no bundler, no npm dependencies. It deploys by pushing a folder and it loads instantly on a bad phone at a birthday party, which is the only performance test that matters here. No model runs in the shipped product. AI was the build method, not the feature.',
      },
    ],
  },
  {
    slug: 'bad-cards-platform',
    title: 'Platform & Growth',
    company: 'Bad Cards',
    thumbnail: '/portfolio/badcards-platform-hero.png',
    thumbnailColor: '#0d0d0d',
    images: ['/portfolio/badcards-platform-hero.png'],
    description: 'Bad Cards is a modern party-gaming platform built to turn internet culture into playable moments across web, Discord, Twitch, and community-driven surfaces. Led end-to-end product, creative, and distribution strategy \u2014 designing a flexible system that allows games, card packs, and mechanics to evolve as fast as culture itself.',
    stats: [
      { value: '10M+', label: 'Players across web and Discord' },
      { value: '2.7M', label: 'Users in 2025 (7x YoY from 430K)' },
      { value: '$0', label: 'Paid marketing, ever' },
      { value: '19.4%', label: 'D30 retention (industry: 2\u20134%)' },
      { value: '14.7%', label: 'D7 retention (industry: 8\u201312%)' },
      { value: '500K+', label: 'Email subscribers, 43% open rate' },
      { value: '91%', label: 'Reduction in infra costs in 2025' },
      { value: '6M+', label: 'Custom cards created by users' },
    ],
    sections: [
      {
        title: 'Discord Activity (Launched August 2025)',
        body: 'Rather than advertising to Discord users, launched as a native Discord Activity enabling instant group play directly inside servers. Cost to build: $8,500. Results: 2M+ users since August, 400K+ email subscribers, played in hundreds of Discord communities.',
        image: '/portfolio/badcards-discord-gameplay.gif',
      },
      {
        title: 'Twitch Extension (Just Launched)',
        body: 'Built a Twitch Extension that lets creators host interactive games directly with their audience in real time. Cost to build: $7,000. Early results: one creator getting over 3,000 concurrent users on their weekly game night.',
        image: '/portfolio/badcards-twitch.gif',
      },
      {
        title: 'Reddit Game (Coming Soon)',
        body: 'Exploring a Reddit-native game designed to live inside subreddits themselves. Cost to build: $1,000.',
        image: '/portfolio/badcards-reddit.gif',
      },
      {
        title: 'The Bigger Picture',
        body: 'Bad Cards is proof of concept for Playable \u2014 a platform for interactive party games that turn audiences into participants. The same product, distribution, and monetization playbook applied across new game formats including HeadRush and KnowItAll Trivia.',
      },
    ],
  },
  {
    slug: 'gametime-12-days',
    title: '12 Days of Gametime',
    company: 'Gametime',
    thumbnail: '/portfolio/gametime-hero.png',
    images: [
      '/portfolio/gametime-hero.png',
      '/portfolio/gametime-screen2.png',
      '/portfolio/gametime-screen3.png',
    ],
    description: 'Design and launch a holiday activation to drive installs, re-engagement, and seasonal brand momentum during a peak ticketing window. Built and launched cross-channel in under three weeks across CRM, social, PR, and influencer partnerships.\n\nThe original recommendation was to validate the activation through owned and high-intent channels first, then scale distribution once performance was proven. Due to timing and seasonal goals, the campaign launched as a hybrid, pairing performance-led mechanics with a large-scale partner amplification. This structure allowed us to test both experience quality and distribution efficiency in a single window.\n\nFully custom interactive microsite with daily giveaways, streak mechanics, referrals, and lifecycle integrations.',
    stats: [
      { value: '12,629', label: 'Registrations' },
      { value: '14%', label: 'Install rate' },
      { value: '5,700+', label: 'Reinstalls / app opens' },
      { value: 'High', label: 'Repeat behavior & high-intent actions' },
    ],
    sections: [
      {
        title: 'What Worked',
        body: '- Activation mechanics performed well: Users who arrived understood the value and returned repeatedly.\n- Owned channels drove the highest-quality growth: CRM materially outperformed all other channels, converting at significantly higher rates.\n- Execution under compression: Cross-functional teams shipped a complex, branded experience on a highly compressed timeline.',
      },
      {
        title: 'What We Learned',
        body: '- Broad partner amplification underperformed materially: ~50M estimated effective audience, ~9,700 non-email entrants, ~0.01\u20130.02% conversion rate.\n- The gap was driven by audience intent mismatch, not creative or product friction.',
      },
      {
        title: 'Outcome & Business Impact',
        body: 'Running this test at scale created clarity. The results validated the original recommendation to prioritize high-intent distribution before broad amplification and directly informed a shift in channel strategy. That shift helped eliminate repeated inefficient spend and supported an estimated ~$5M in annualized cost savings through smarter partner selection, clearer performance thresholds, and tighter campaign scoping.',
      },
    ],
  },
  {
    slug: 'ditch-your-site',
    title: 'DitchYourSite',
    company: 'Other',
    thumbnail: '/portfolio/ditchyoursite-hero.png',
    images: ['/portfolio/ditchyoursite-hero.png'],
    description: 'DitchYourSite is an AI-powered website migration tool that scrapes any public website and outputs a complete migration kit \u2014 structured JSON, downloaded images, and a pre-written Claude Code prompt \u2014 ready to rebuild the site as a modern Next.js application. Built and shipped in under 48 hours from concept to live product with payments.\n\nLeaving Squarespace, Wix, Showit, or any legacy website builder is painful. The platforms don\'t give you your content back in a usable format. Designers charge $3\u20135K to rebuild. Manual migration takes days. There was no fast, affordable, self-serve path from "I hate my website" to "I have a new one."\n\nPaste a URL. Click Scrape. Get a ZIP file containing everything needed to rebuild the site with AI \u2014 all pages, all images, full text content, nav structure, and a ready-to-paste Claude Code prompt. The entire migration goes from weeks to hours.',
    stats: [
      { value: '48hrs', label: 'Concept to live product' },
      { value: '$0', label: 'No agency, no team' },
      { value: '$2.99', label: 'Entry price per scrape' },
      { value: '6', label: 'Platforms supported' },
    ],
    sections: [
      {
        title: 'Technical Stack',
        body: 'Next.js 14, TypeScript, Tailwind CSS, Puppeteer + Chromium, Supabase, Stripe, Vercel.',
      },
      {
        title: 'Key Features',
        body: '- Multi-platform support with platform-specific URL placeholders\n- Brand kit generator: upload logo and screenshot, system generates brand guidelines\n- 4 mini-games that load while the scrape runs (Ditch Digger, Whack-a-Web-Builder, Jail Break, 404 Dodger)\n- Free tier: 10 pages, text only. Paid: 50 pages, full ZIP, all images. Pro: $20/month, 250 scrapes',
      },
    ],
    link: 'https://ditchyoursite.com',
  },
  {
    slug: 'personalityhire-ai',
    title: 'PersonalityHire.ai',
    company: 'Other',
    thumbnail: '/portfolio/personalityhire-hero.png',
    images: ['/portfolio/personalityhire-hero.png'],
    description: 'A lightweight Slack bot built solo using AI-assisted coding tools including v0.dev and ChatGPT. The bot sends randomized, chaotic-good messages to keep teams entertained, with admins able to add custom messages.\n\nHandled ~90% of the build solo, then brought in an engineer for final polish and Slack submission. A fun experiment to test AI-assisted development capabilities.',
    stats: [
      { value: '~$250', label: 'Total cost to build' },
      { value: '10\u201312hrs', label: 'Total build time' },
      { value: '~90%', label: 'Built solo' },
    ],
    link: 'https://personalityhire.ai',
  },
  {
    slug: 'creative-marketing-ops-playbook',
    title: 'Creative + Marketing Ops Playbook',
    company: 'Other',
    thumbnail: '/portfolio/aaba8d72-52ea-42fe-9073-3942f84fdeb9_car_1x1.png',
    images: [
      '/portfolio/849d33ed-f9e6-4a23-bfbe-fd2d7f1f0018_rw_1920.png',
    ],
    description: 'Need resources to help your team\'s creative operations? I got you.\n\nI created a 30+ Page Creative + Marketing Ops. Playbook includes brief templates, DACI modeling, naming convention guides, decision-making frameworks, and more!',
    link: 'https://docs.google.com/presentation/d/1dnR3r5PtQ2aM2Sim25tCwKgD7Q1RzPFKXrigFCGgAF8',
  },
  {
    slug: 'process-implementation',
    title: 'Process Implementation',
    company: 'Lyft',
    thumbnail: '/portfolio/7f8819e9-f0ad-4bb4-a3c7-8113e4666fad_rwc_0x0x1746x1746x1746.png',
    images: [
      '/portfolio/2d6c3d25-704c-4a4d-b614-b1f06058019c_rw_1200.png',
      '/portfolio/3c8ad011-ec0f-4df4-aa74-0a5caf26d460_rw_1200.png',
      '/portfolio/085a43b8-6c13-430b-9784-a9d07f0b38ae_rw_1200.png',
      '/portfolio/9c55b63f-a631-4bdd-a219-0d9a3dbdbafd_rw_1200.png',
      '/portfolio/7a9b7a21-2f6a-4c35-8a52-88eca6989fa1_rw_1200.png',
      '/portfolio/3adaa6b8-10fd-41b0-80db-9a373628ee75_rw_1200.png',
      '/portfolio/fd778a13-ca1c-45df-9eb0-eeb72459f698_rw_1200.png',
    ],
    description: 'This is typically given in a presentation, and I\'d love to connect to walk you through it. In the meantime, here is what this page covers:\n\nName a process that I\'m most proud of spearheading and implementing, which significantly impacted my team\'s productivity. The following slides walk through the process that I built and implemented at Lyft, which followed me to many other roles.',
    thinContent: true,
  },
  {
    slug: '12-days-of-momo',
    title: '12 Days Of Momo',
    company: 'Concept Labs',
    thumbnail: '/portfolio/cd05c55c-3120-425b-b714-6c01f31b423f_rwc_337x0x1017x1017x1017.png',
    images: [
      '/portfolio/4724e046-8025-40b3-8aef-0f8cd9b5eb05_rw_1920.png',
    ],
    description: 'Working with 9x Emmy-award-winning animation studio, Baobab Studios, we collaborated to bring the Momoguro universe to life. We were tasked with creating an interactive holiday activation for Momoguro. We made an advent calendar where users could claim "tickets" by entering them into a raffle for allowlist spots. This interactive experience brought users into a snowy plain that they could enter every day for 12 days.\n\nOur Services/My Oversight:\n- Creation of an interactive 3D advent calendar\n- Development of website and form flow\n- Social plan and launch\n- Marketing and Creative Direction\n\nVisiting the Website was not a CTA — so we felt this was a great success metric. Not only did people participate, but they were engaged enough to go to our website to learn more about our services.\n\nThe team worked incredibly hard on this with a tight turn, and the results speak for themselves. It was an incredibly challenging but fun activation that was engaging and produced an amazing return.',
    stats: [
      { value: '368,358', label: 'Total Entries' },
      { value: '55,245', label: 'Unique Entrants' },
      { value: '97,832', label: 'Tweets / Shares' },
      { value: '40,351', label: 'Followers Gained' },
      { value: '4,300+', label: 'Newsletter Signups' },
      { value: '24,000+', label: 'Website Visits' },
    ],
  },
  {
    slug: 'robinhood-you-got-it',
    title: 'You Got It',
    company: 'Robinhood',
    thumbnail: '/portfolio/9dfe4c52-a25d-47d4-8020-873412eddac3_rwc_720x0x1844x1844x1844.png',
    images: [
      '/portfolio/d7723cfe-14ed-4b14-a20e-813ccce6b55b_rw_1200.png',
      '/portfolio/f53d6c90-94fe-4ff9-91dd-1bbabdf12d1a_rw_1200.png',
      '/portfolio/2af8669a-4c87-46bb-9ea8-de450ae18fde_rw_1200.png',
      '/portfolio/c94e6dad-2c91-4d1c-9d1c-16343bff95ee_rw_1200.png',
    ],
    description: 'January 28th hit the company when we didn\'t have a creative team dedicated to social. With much of the group stuck on our brand design systems or building educational content, we needed thought and design leadership to help develop social content/strategy.\n\nMoving quickly, I took a few days to sit in some customer feedback sessions with the research team and developed a very high-level strategy for social. The upper left image on the grid below shows the social pillars I crafted, which became the foundation for the social crisis strategy.\n\nAfter activating the team on some educational content, the c-team quickly wanted creative ideas to combat the negative chatter from a group they called "The Fringe Fighters." (people who were on the fringe/cusp of leaving Robinhood). That night, I created storyboards to present ideas to help combat the negative social media discussion. CS + team responded favorably to these ideas and asked us to align one of them with the pillars above.\n\n"You Got It" fit the bill. It highlighted some of our product features and added a level of transparency on things we are building for the future. This concept also performed the best in our research/testing. Working with our agency partner, we produced the video and planned to target a specific audience with the cut.\n\nLearnings: Looking back, I would have tested these concepts without music. I think the team got excited about using a song like "You Got It," but the reality of that was slim. In turn, when we had to change the music due to budget constraints, it felt like the project lost a bit of steam.\n\nI am reluctant to say this because I love data, but I wish we focused less on testing these concepts. Not because I don\'t think the research was valuable, but testing lost us quite a few weeks. The original ask was to have this turned around quickly, so it felt like a blocker that we would start testing ads now (when we have never tested ads in the past.)\n\nI also would have liked to work with agency partners who could execute faster. Our AOR took more than four weeks to produce this short video, and at the end of it all, we still needed to have an internal team member clean it up. With how much lifting the storyboard did, it should have been as simple as handing that off to an editor and having them make the cuts.\n\nThough there were quite a few hiccups, I feel I learned a lot from that experience and loved seeing farfetched concepts come to life.',
  },
  {
    slug: 'concept-labs-rebrand',
    title: 'Rebrand Strategy',
    company: 'Concept Labs',
    thumbnail: '/portfolio/54e1b0a5-ec2a-4a4e-81b4-96a52e9be3e7_rwc_458x80x847x847x847.jpg',
    images: [
      '/portfolio/f9dc1753-24e4-4dd9-9bc3-afa58b6a85ba_rw_3840.png',
      '/portfolio/ded50621-70e9-40b9-92ae-41a0f4544f77_rw_3840.png',
      '/portfolio/13c7c303-0431-4ebb-bf30-ff015655711d_rw_3840.png',
      '/portfolio/9bd7c9f3-59fd-4c18-b4e6-cab6f6c8135e_rw_3840.png',
      '/portfolio/0db7858e-32b6-479e-8998-e6d4565480a6_rw_3840.png',
      '/portfolio/c9864ad8-b50f-4a22-86e9-355d5749abec_rw_3840.png',
      '/portfolio/e81adc9b-61ba-411b-8f04-4b0a2d87ffb1_rw_3840.png',
      '/portfolio/1bd7d328-1405-42aa-ad26-9cd32ad1eae8_rw_3840.png',
      '/portfolio/da40ac93-a482-4ccb-8ec9-d68c6e24a4b3_rw_3840.png',
      '/portfolio/e34ef738-d152-4b8a-93c4-cad07277da29_rw_3840.png',
      '/portfolio/16cb9f46-c6a0-42e2-b45d-28fa041d7d47_rw_3840.png',
      '/portfolio/da991e32-332c-4861-9b42-533bee961d27_rw_3840.png',
      '/portfolio/91781357-8d3b-4057-9f40-ee37ee0cca50_rw_3840.png',
      '/portfolio/12a3db7d-6e7a-45f2-9cfd-630c02d87559_rw_3840.png',
      '/portfolio/c16fa195-cd61-4658-9695-62cb407fb32f_rw_3840.png',
      '/portfolio/8732aa31-15a3-4be1-ba11-f51f11a7b153_rw_3840.png',
      '/portfolio/040b33db-3ee7-475d-aafa-df0d3955b792_rw_3840.png',
      '/portfolio/f0f60fff-abfe-4c7b-801b-02ee633576c0_rw_3840.png',
      '/portfolio/e195732a-1571-4828-9bef-a254a0acaa68_rw_3840.png',
      '/portfolio/a741092b-059e-475a-8550-4882d526f414_rw_3840.png',
      '/portfolio/e50bf48b-cbeb-4888-b235-4f647a4bd09d_rw_3840.png',
      '/portfolio/710f84b6-8347-4b44-9290-f0b84332bf32_rw_3840.png',
      '/portfolio/823a3f14-e9d2-4a78-a48c-5d951f94600a_rw_3840.png',
      '/portfolio/0742454b-fb45-427f-a51a-d360615c8d7e_rw_3840.png',
      '/portfolio/80b86606-03dd-42f3-bf17-e6f30e0c4c8e_rw_3840.png',
      '/portfolio/ff5b8c0b-8381-44f6-8004-5096c06e0d8d_rw_3840.png',
      '/portfolio/33c266fe-4086-43fb-8298-463efe2c4a7c_rw_3840.png',
      '/portfolio/c41452c0-b108-4360-b4f6-a95ce07a9c32_rw_3840.png',
      '/portfolio/c5eae02b-70f4-46a4-8c5b-5926d8b5fa2c_rw_3840.png',
      '/portfolio/3ab4934e-132d-4d4d-b6fc-c1ee9af6b66d_rw_3840.png',
      '/portfolio/019390da-4f5b-4b2d-95ed-e66c72f91ebf_rw_3840.png',
      '/portfolio/cdbc0358-14e4-493a-9ede-9254d5a95aee_rw_3840.png',
      '/portfolio/ea37d9a6-9590-46af-bd0f-85a2b2389e9d_rw_3840.png',
      '/portfolio/2e010a1f-51ee-49b3-83ef-61b201b452f6_rw_3840.png',
      '/portfolio/2bfab00c-1a76-41a7-b1a3-bffcf9e6cd4e_rw_3840.png',
      '/portfolio/4ed8ebda-a458-444a-8364-da49e9d7042a_rw_3840.png',
    ],
    description: 'Transitioning a 15-year-old AAA art agency to a creative and marketing powerhouse while keeping the built equity from the old name, "Concept Art House."\n\nResponsible for: Rebranding and design, brand strategy, design systems, creative positioning, voice and tone, social strategy, campaigns, pitch work, and more.\n\nStrategy, Artboard, and Concepts',
  },
  {
    slug: 'y-lyft',
    title: 'Y Lyft Brand Campaign',
    company: 'Lyft',
    thumbnail: '/portfolio/c39f7928-7efe-4005-a732-d01c481eb749_rwc_211x0x540x540x540.png',
    images: [
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/487c9ac8-fc22-4072-a63a-686ce0f25080_rw_1200.png?h=26d638c00c8d5620b7d5565fd81ead0b',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/240b7b9a-1ee2-4460-a528-eab89ff3224c_rw_1200.png?h=ed6312beaa88bef14583654babc9e593',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/f3f42914-7e7e-4201-9a76-b4fead12dca4_rw_1200.png?h=3d4be179a837420e4d328871a58a873b',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/1824d61d-733e-4b2c-b650-6c560e90c0f6_rw_1200.png?h=43198ed1997ef30f07bc00862f9c0969',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/2c6e09bf-f9f6-49ac-b359-76c480980b56_rw_1200.png?h=a4114cae9d19b0296c53a447bdfc650d',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/277458b3-1218-4d66-a0bc-9cb54977d6e1_rw_1200.png?h=22288115e77670726571854b4e30f44c',
    ],
    description: 'This is typically given in a presentation, and I\'d love to connect to walk you through it. In the meantime, here is what this page covers:\n\n"Think about a previous project/brand campaign I\'ve managed that required complex tracking of multiple deliverables and various stakeholders and walk us through the project from inception to launch."',
    thinContent: true,
  },
  {
    slug: 'bad-cards-rebrand',
    title: 'Rebrand',
    company: 'Bad Cards',
    thumbnail: '/portfolio/7264a83d-2bdc-4854-8169-0fc89b60ec7a_rwc_445x121x1031x1031x1031.jpg',
    images: [
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/7d2e7ab7-c134-4d78-889f-6ea6a6baf681_rw_1920.gif?h=110126c927a59319e98fa490bb68e4ea',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/48bdc686-7d68-43eb-97ff-2f15ccfd604a_rw_1920.jpg?h=7ad3746b08567543cfafe9cd24f8d8db',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/a8afaf61-63ea-4949-83cb-f366b59d3eeb_rw_1920.jpg?h=8bdbb9ac98221b10d03bdb96b78cad96',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/cb110bef-f829-482c-b6b2-1322bc629f4a_rw_1920.jpg?h=4618d19445d1b4bd477799f7d1078bc9',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/c4e56640-57b7-4853-89df-ce635d6471f6_rw_1920.jpg?h=97f64225c05d28bc9845a8e9d17e9746',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/4d56923c-84c2-432a-94dd-8e0274d2cd07_rw_1920.jpg?h=46b06aa02ba8ff143b98b91446f3ca25',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/8dbb09a1-3faf-438b-b67a-7be06719c14f_rw_1920.jpg?h=0512ff536b5aec1dc706976103242ca1',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/3844459a-252a-4e66-a639-6e9d7abe4e0e_rw_1920.jpg?h=8ca74b5c7130dd367a402c596ba3c8a1',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/3c0daf1a-6f17-4ad3-b4da-ec4a39872334_rw_1920.jpg?h=6ddfabd98dbcf662a2cd5b1072061e6f',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/c2ed324f-798f-4d49-9b3a-3665e6614c7e_rw_1920.jpg?h=846562bd2255c11f0b8674f8ee0b5daa',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/cc7d0dec-e43b-4c26-aa91-bc3a3a4db506_rw_1920.jpg?h=19528ed17a2a9dc3f0b88205a08ac0d1',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/7f96850a-d43c-4f7d-bbb3-646c847b0bde_rw_1920.jpg?h=536fe29fedc60fdb1f23ba8eb11629a5',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/e99780fc-51f6-429f-8b14-a8c7520c30bc_rw_1920.jpg?h=ec747333e72cf93b6b7ae18fde364a50',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/44dd7195-f082-45ce-8151-acc724b5388a_rw_1920.jpg?h=2a83f96715c40a47d9c50844d095e94d',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/f4db3676-2c2f-474c-87ef-9672703fcbd9_rw_1920.jpg?h=5e93171bbfd17d05ad9b3da3a413d5ab',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/82580a83-7187-43b8-befd-332b59a29d83_rw_1920.jpg?h=d190144d9c95e0d84357c4261d0ce88d',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/17a91374-650c-49ad-a831-aed2b9fce7cf_rw_1920.gif?h=91cd77ef976f232abb695aed924b980a',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/5a692da0-fd0f-44aa-a6f3-2136ac025611_rw_1200.png?h=78984e8c26451a9c0b7b2c50ffc58da3',
    ],
    description: 'Rebranding outdated design to present Bad Cards as an innovative online party game.\n\nResponsible for: Rebranding and design, brand strategy, design systems, creative positioning, voice and tone, social strategy, campaigns, pitch work, agency management, and more.\n\nAgency: monga.design',
    imageLabels: { 17: 'Look prior to rebrand' },
  },
  {
    slug: 'robinhood-creative-support',
    title: 'Creative Support',
    company: 'Robinhood',
    thumbnail: '/portfolio/a222145e-adfb-4eb5-bd14-1ed12ab50c3f_rwc_0x0x1008x1008x1008.gif',
    images: [
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/e1295db5-0315-4142-a4c0-2598df9e1bbd_rw_1200.gif?h=f01325b76c8831edfcfef106f6b435af',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/45f62b91-7df6-4532-aaf9-95e932961de1_rw_600.gif?h=672d4c40fbadf17b7001ba1a6bc1140b',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/1dec4a53-880c-4675-8967-04d4dc9a2b83_rw_600.gif?h=2b5f258fb14c1c8d4ac492c1e3fc106d',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/c8ee9252-cf5f-420b-bb8c-857a605bf4dc_rw_1200.png?h=fa287af3d9dc266fc54c1c46513fae21',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/00d29559-e2c1-4489-8792-a460dc2db5da_rw_1200.png?h=ea30a398a793eacb77c189e95ee14c77',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/e20c0087-31fa-485b-9f4c-066be2b29c6a_rw_1200.png?h=d23899d1d20e89151554ae7e19ddfe7c',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/3ca4871a-c44e-4859-aa6e-64f2c6ed4aba_rw_1200.png?h=4a5423ed8df7e0575e8b627184d73ffd',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/d28e6402-4381-4c39-9de6-c9f28de31de9_rw_1200.png?h=521f2245c656eab4f3f114df69907b24',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/801fa2a3-77c1-40ab-b6a9-68bdd77c59ab_rw_1200.png?h=cc27b4410d4ea7b3d6b0c71e1c1ed942',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/b561d215-b567-4012-b9a3-b0cec9637dbd_rw_1200.png?h=f806ce06b1daa30c2a5ec72fe060ae01',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/a8fb819b-c98d-4196-885c-193402c01c3e_rw_1200.png?h=4400d6d312c4f1bc7162750e0e141798',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/aaf34b59-acc4-437d-a378-30267d70df9d_rw_1200.gif?h=199aec987fd8ced79b2c44d28d8cb339',
    ],
    description: 'Various samples of design support I\'ve provided while at Robinhood. Some work was leveraging templates while other work was net-new.',
    sections: [
      {
        title: 'DogeDay Wink',
        body: 'Challenge: Create a post for Twitter that celebrates DogeDay without bringing too much attention or looking like a recommendation.\n\nSurprise and delight is key \u2014 so I decided to make our simple Doge boi (original design by one of our brand designers) wink at his fans.\n\nMetrics: The RH Tweet was the second most interacted with/trending DogeDay post.',
      },
      {
        title: 'Curiosity Effect Growth Giveaway',
        body: 'There was a lot of chatter about Reddit\'s Super Bowl ad after the game. If you don\'t know much about it \u2014 they ran a 5-second ad and leveraged what\'s called the "curiosity effect." I pitched an idea that we do something similar with our giveaways. This design is a sample of how that idea could work/look.\n\nThe idea is that it would be a GIF, and our audience would need to pause it at the proper time to get the details.',
      },
      {
        title: 'Hot Minute with Meg',
        body: 'Objective: Engage a diverse audience of investors \u2014 giving them quick tips on how to invest, use RH, and more with Megan Thee Stallion.\n\nStrategy: Get some star power behind our social media. Engage a new audience, and walk through Megan\'s story on how she became an icon (and an investor).\n\nApproach: 60 second videos for IG/Reels/TikTok that highlight different features of Robinhood and Megan\'s journey.\n\nCadence: Content Series \u2014 6\u20138 episodes.',
      },
      {
        title: 'This Week In Crypto (Production Design)',
        body: 'With the bandwidth constraints, I will occasionally jump in to help with various projects like TWIC, Blog Headers, etc. Why? I write the letters "JAV" in the front of every notebook I own. It stands for "just add value." It\'s a subtle reminder that it\'s not about the role; it\'s about the goal. I am here to help the team when/how I can.',
      },
    ],
  },
  {
    slug: 'airpr-brand-development',
    title: 'Brand Development',
    company: 'AirPR',
    thumbnail: '/portfolio/8a342c3f-6f45-44e1-9334-e5d75ad9fb87_rwc_0x0x1693x1693x1693.gif',
    images: [
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/f99cb068-244a-4144-b36f-0be13c6ec2a9_rw_600.png?h=8045d7fe70a34485bdaf29691f561cfd',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/9c67c2d2-7a6e-42d3-ac4b-23b6560349ca_rw_600.jpg?h=b040efb5f340429b9893dc541e4418ed',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/b4e882b8-b49f-4d84-b385-a2b271b01b59_rw_600.jpg?h=486310f7e0ced76a45fa26835054b54b',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/1b19838a-2327-44f2-8b65-20834585e0f1_rw_1200.jpg?h=855c7d5ae55f02980dd1f1dd6adcdecd',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/354fa716-1c69-4d6a-9aa6-42b0bc580bda_rw_1920.jpg?h=ea05a4ea67c939114fa15b2ebcee1e3f',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/7f908d19-0fde-45a8-9da3-4f7da932425a_rw_1920.png?h=2c4a9780454ed31bdd81b0beabea57ac',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/ffd77a9a-b551-4775-8766-e28f174135b6_rw_1200.jpg?h=756cac08a4b86e2b327b0df4aa7ac82b',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/76177abd-c552-4899-ae55-9cd775f59715_rw_1920.jpg?h=6ffc1efe55b3a1ec81aa027d9033b8c0',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/6f38b709-121e-4815-b339-4f0ec78dd2ed_rw_1920.jpg?h=4928fd65a12718b19a9ec55fde65d53e',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/79a152d4-ba38-4af5-9a70-cdca6d74943d_rw_1920.jpg?h=ce890db72f5b4d3ab6743fdefce3271e',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/6051e707-0fee-4356-a8b8-416d32b020e4_rw_1200.jpg?h=e65664f501360d1e72b66afc1d2a9914',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/72306862-e56a-4bcf-9fc6-1458c54b66a1_rw_1920.jpg?h=444f59bed6af7eb14fffbfbdb4843373',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/20565879-b346-4f4f-8f41-bd4aea9b2629_rw_1920.jpg?h=e4c64cf1ae3ae4566ee85513795b2913',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/3d00d1b9-792d-42c2-b727-4039aeb83edc_rw_1200.jpg?h=fb87bd846c16fc1a8d8c05db722e91ab',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/dc9b584a-281f-4489-8c5b-6a7f06a87611_rw_1200.jpg?h=9969205802339db3c8018cc6d86e153a',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/6cf792ee-59d5-438a-ab5b-15110614766b_rw_1200.png?h=e881a04e79a70be6528c4807b91dcb0a',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/653689c5-ad6c-48c2-896d-79d71724fccc_rw_1200.png?h=390ee111128e17fb0842a3741b957ea3',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/164016d5-ba36-4413-acdd-04ef6d4b2f5a_rw_1200.png?h=d16749801b601f5e16ddee090c589bf1',
      'https://cdn.myportfolio.com/0b016d8a836e89dbab66b15317ee8de6/a45d1e9c-fa5e-4202-bc80-419636d4fa4b_rw_1200.png?h=9c1b827ff9c48838eb8eef22ed65a49a',
    ],
    description: 'I was tasked to reimagine/develop the AirPR brand with many limitations. We had some older stakeholders that didn\'t like change, so I needed to develop things in ways that weren\'t far off from what they currently had, and had to justify every move.\n\nOn my first day, the Marketing team provided me with this. AirPR had been working with d-level agencies and low-res images for years and knew they needed to step up their brand presence if they ever wanted to make waves in the space. However, some older stakeholders were very partial to the current look and didn\'t want to change much.',
    sections: [
      {
        title: 'Step 1: Simplify',
        body: 'One major complaint that the team had was how difficult it was to make the logo look good on any print piece, swag item, screen, 1-pager, etc. We identified the main factor playing into that was the logo\'s complexity (shadow under the icon, gradient, etc). We also recognized that the brown color in "AIR" clashed with a lot of their work.\n\nFrom my perspective, simplicity helps create good design. I worked diligently with the team to help simplify the logo, develop a color palette, and flatten the images.',
      },
      {
        title: 'Step 2: Consistency',
        body: 'With executive leadership on board, I worked to develop a brand style guide. The team didn\'t recognize the importance of consistency across their marketing materials. Fonts were randomly selected, colors chosen on the season, and presentations were filled with inconsistent illustration styles.\n\nWe started simple and created a baseline style guide. Every email, PowerPoint presentation, and ad began to fit within these guidelines. I worked with the UX team to help change design elements in our software UI.\n\nHighlight: We did an email campaign with some high-level case study results in a banner image in this style. Typically the click rate of the emails was around 14%, but with the new images, we saw an 18 point increase.\n\nLearnings: I would have worked to get more budget for this project. We had a small team and little to spend, but I should\'ve pushed more and developed guidelines around voice and tone, photography, illustrations, etc.',
      },
      {
        title: 'Step 3: Execution',
        body: 'One of my favorite things about being a designer and creator is seeing what I create come to life. From digital/print ads to OOH and conference materials, seeing people respond and interact with a design is gratifying.\n\nSomething I\'m proud of is seeing our hard work come to life at the annual AirPR conference. I was responsible for designing, ordering, printing, hosting, and project managing for this event.\n\nThis is just a taste of how we brought the new brand look and feel to life.\n\nAfter some user research, we recognized that the name "AirPR" was misleading. Many assumed that we were a PR agency vs. a SaaS company \u2014 which kept us from many executive-level conversations at prospect companies.\n\nOur tag line was "the story is in the data." I presented a new name, "Datell" (day-tell), and got support from all but two of our board of directors. This effort was started during my transition out of AirPR and dropped after I left. It turns out one opposing director had the rights and the URL to "Onclusive."\n\nThough it felt like our hard work didn\'t pay off, I am grateful for the experience of helping a technology company go through the rebranding process.',
      },
    ],
  },
]
